In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([[4],[5],[6]])
print (arr1.shape)
print (arr2.shape)
res = arr1*arr2
print(res)

(3,)
(3, 1)
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [4]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([4,5,6])
print (arr1.shape)
print (arr2.shape)
res = arr1*arr2 
print(res)

(2, 2)
(2,)
[[ 4 10]
 [12 20]]
