In [1]:
import numpy as np

In [2]:
arr  = np.array([1,2,3,4])
print(type(arr))  #end dimentional array
print (arr)

<class 'numpy.ndarray'>
[1 2 3 4]


In [3]:
mul_arr = np.array([[[1,2,3,4],[7,8,9,74]],[[1,2,3,4],[7,8,9,74]]])
print(mul_arr)

[[[ 1  2  3  4]
  [ 7  8  9 74]]

 [[ 1  2  3  4]
  [ 7  8  9 74]]]


In [4]:
li = [1,2,3,4,"KO"]
liarr = np.array(li)
print(liarr)

['1' '2' '3' '4' 'KO']


In [5]:
np.linspace(5,7,7) #first one is upper-bound and 2nd one is lower bound and third one is how many you value needed

array([5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        ])

In [6]:
np.arange (5,20,2) #third one is the gap

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
np.random.uniform(5,10, size = 5)

array([5.18176807, 9.76358597, 7.84868038, 7.72645103, 8.39097194])

In [8]:
np.random.uniform(5,10, size = (5,3))

array([[6.24038131, 8.29197725, 9.98869216],
       [6.51081571, 9.32845804, 8.22428405],
       [5.32214538, 6.68835012, 5.65409695],
       [6.43304376, 6.63581559, 5.83865316],
       [9.83671981, 7.47846961, 7.05047293]])

In [9]:
np.logspace(5,20,8, base=2)

array([3.20000000e+01, 1.41323458e+02, 6.24134991e+02, 2.75640359e+03,
       1.21732652e+04, 5.37614979e+04, 2.37430024e+05, 1.04857600e+06])

In [10]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.ones((2,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
np.full((2,3), fill_value=3)

array([[3, 3, 3],
       [3, 3, 3]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
lit = [1,2,2,3,4,5,6,6,96,-96]
arr1 = np.array(lit)
print(arr1)

[  1   2   2   3   4   5   6   6  96 -96]


In [15]:
np.min(arr1)

1

In [16]:
np.max(arr1)

96

In [17]:
np.unique(arr1, return_counts = True)

(array([ 1,  2,  3,  4,  5,  6, 96]),
 array([1, 2, 1, 1, 1, 2, 2], dtype=int64))

In [19]:
np.mean(arr1 , dtype='int')

22

In [20]:
np.median(arr1)

4.5

In [21]:
list2 = [0.1,0.3,2.5,1.9]
arr2 = np.array(list2)
bins = np.array([0,1,2,3,4,5,6,7])
np.digitize(arr2,bins)

array([1, 1, 3, 2], dtype=int64)

In [24]:
df = np.random.randint(14,size =(4,3))
print(df)

[[12  5  9]
 [ 2  5  7]
 [ 3  3  0]
 [ 0  5  6]]


In [25]:
df.reshape(3,4)

array([[12,  5,  9,  2],
       [ 5,  7,  3,  3],
       [ 0,  0,  5,  6]])

In [40]:
 cd =df.reshape(-1)
print(cd)

[12  5  9  2  5  7  3  3  0  0  5  6]


In [34]:
np.expand_dims(cd,axis=0)

array([[12,  5,  9,  2,  5,  7,  3,  3,  0,  0,  5,  6]])

In [36]:
np.expand_dims(cd,axis=1)

array([[12],
       [ 5],
       [ 9],
       [ 2],
       [ 5],
       [ 7],
       [ 3],
       [ 3],
       [ 0],
       [ 0],
       [ 5],
       [ 6]])

In [47]:
mul_arr1 = np.array([[[1],[3]],[[8],[5]]])



In [48]:
squeeze = np.squeeze(mul_arr1)

In [49]:
print (squeeze)

[[1 3]
 [8 5]]


In [50]:
np.argmax(arr1)

8

In [51]:
np.argmin(arr1)

0

In [54]:
np.abs(arr1)

array([ 1,  2,  2,  3,  4,  5,  6,  6, 96, 96])